template: testify
packages:
  github.com/hihikaAAa/GoProjects/url-shortener/internal/http-server/handlers/url/save:
    config:
      dir: "{{.InterfaceDir}}/mocks"     
      filename: "urlsaver_mock.go"
    interfaces:
      URLSaver: {}                       
